# site settings
title: Researchsio
email: researchsio.org@gmail.com
description: 
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: MD. Salman Faisal
street_address: 217/218, Road /#3, Block Cha, Section 2, Mirpur
city: Dhaka North City
state: Dhaka
zip_code: 1216
country: Bangladesh
phone: +8801791925491

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/researchsio
github_url:
googleplus_url: 
instagram_url: https://instagram.com/researchsio
linkedin_url: https://www.linkedin.com/in/researchsio-6059601a4/
pinterest_url:
slack_url:


# build settings
markdown: kramdown

sass:
  style: compressed
plugins:
- jekyll-seo-tag
